name: CI/CD - Modulo 1 Acortador de URLs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.5.7

jobs:
  test:
    name: CI - Pruebas Unitarias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias de prueba
        run: pip install pytest boto3 moto

      - name: Correr pruebas unitarias
        run: pytest lambda/test_handler.py -v

  deploy:
    name: CD - Deploy Terraform
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          export CHECKPOINT_DISABLE=1
          terraform init -upgrade

      - name: Terraform Import DynamoDB
        run: terraform import aws_dynamodb_table.urls parcial3 || true

      - name: Terraform Import IAM Role
        run: terraform import aws_iam_role.lambda_role modulo1-acortador-role || true

      - name: Terraform Import IAM Policy
        run: terraform import aws_iam_role_policy.lambda_dynamodb_policy modulo1-acortador-role:modulo1-acortador-dynamo-policy || true

      - name: Terraform Import Lambda
        run: terraform import aws_lambda_function.acortador modulo1-acortador || true

      - name: Terraform Import API Gateway
        run: terraform import aws_apigatewayv2_api.http_api pyxidvyl0f || true

      - name: Terraform Import API Stage
        run: |
          terraform import aws_apigatewayv2_stage.default 'pyxidvyl0f/$default' || true

      - name: Terraform Import API Integration
        run: terraform import aws_apigatewayv2_integration.lambda_integration pyxidvyl0f/tojwrno || true

      - name: Terraform Import API Route
        run: terraform import aws_apigatewayv2_route.post_shorten pyxidvyl0f/38h0aca || true

      - name: Terraform Import Lambda Permission
        run: terraform import aws_lambda_permission.api_gateway modulo1-acortador/AllowAPIGatewayInvoke || true

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve